### ISSUE TITLE
Just use Pale Moon

### ISSUE THREAD

**Issue by beerisgood** [CHEF-KOCH/BetterFirefox#15]
You have much less work if you use the Pale Moon browser as base ;)

**Comment by Atavic** [comment]
Totally agree. It's a better start, with more security.

**Comment by CHEF-KOCH** [comment]
Pale Moon is not more secure, in fact it's less secure due fact that there are not that many 'eyes' on this project compared to the original Firefox release, which also is monitored due another fact -> Tor. Using other 'based on' wannabe Browsers is never an solution, it makes things more worse and not helps. Pale Moon not even use the same Engine it use 'Goanna' which in fact makes it to another Browser, which nothing much have anymore to do with Firefox. 

The project here is not to show alternatives, it's o bring Mozilla back on the right course. 

I close this because I not want such talk over here, there is no benefit.
