### ISSUE TITLE
a few suggested things

### ISSUE THREAD

**Issue by jawz101** [CHEF-KOCH/BetterFirefox#20]
Some things on my wishlist:

- advanced searching in about:config.  Like the ability to search for all modified entries
- descriptions for about:config entries within the actual screen.  I'm tired of googling them or being told to read the source code, blog posts, or old mozilla pages.
- for the above, I'd also like to see columns that show what version the key was added in, if it's planned to be deprecated, doesn't actually work yet/anymore, if it's Android/Linux/Windows/Mac only.  Tired of seeing prefs that don't actually do anything.

> No ability to sync all about:config tweaks (you need extra opt-in for that).

you can manually sync additional prefs if you create a new **boolean** for that value prefixed with `services.sync.prefs.sync` and set it to true

ex: if I wanted to enable syncing of my `beacon.enabled` pref it would be
`services.sync.prefs.sync.beacon.enabled` and set it to true

**Comment by CHEF-KOCH** [comment]
You can't sync all about:config tweaks, without doing it manually. This is a no go anyway. I not removed or changed that line because it's still true. Do this for 200+ lines manually, who really does that? In my test the own created lines also never got synced which means you need to redo everything after you installed Firefox again.
