### ISSUE TITLE
New add-on was installed without my permission - Mr. Robot marketing backlash

### ISSUE THREAD

**Issue by licaon-kter** [CHEF-KOCH/BetterFirefox#21]
https://drewdevault.com/2017/12/16/Firefox-is-on-a-slippery-slope.html

https://twitter.com/steveklabnik/status/941709048529014784

https://www.cnet.com/news/mozilla-backpedals-after-mr-robot-firefox-misstep/

**Comment by W4RH4WK** [comment]
Yeah, @CHEF-KOCH and me noticed. It's really hard to overlook.

I spent the last few days thinking about that whole dilemma. My mind is concerned with the consequences, and how the BetterFirefox project should approach this.

My *personal* opinion *at the moment* is that Mozilla should purge the ability of pushing add-ons / plugins from the code base. They have clearly demonstrated that they should not have this kind of power.

At this point I am still fine with telemetry and crash reports. While having them on by default is another topic.

Of course they can always push changes and features via the update process. But I believe / hope they have a much tighter grip on what goes into the main code base compared to add-ons / plugins.

**Comment by CHEF-KOCH** [comment]
I marked it as invalid because the story got pushed way too far and at the end nothing was submitted directly to Mozilla. However I hope Mozilla leaned the lesion and all we can do is now to inform people about the reasons why Mozilla did this and stay in contact with them to avoid that such 'marketing' not happens again. I totally get the argumentation that this is about trust and I get that.

But it's not helpful to point with the fingers now on Mozilla and say 'screw you' - I think to win back some trust is just to remove the ability or give more toggles within the settings to disable remotely addons installation no matter if you opt-in in telemetry/experiments. 

However I will address this immediately and manage this on a higher level because their intention behind it wasn't that bad - it's just only wrong that they did this without any warnings and they have should known it better.
