### ISSUE TITLE
Connections at Mozilla

### ISSUE THREAD

**Issue by W4RH4WK** [CHEF-KOCH/BetterFirefox#9]
Do we have any connections to Mozilla or some information whether they will even care about this?

Or at least heard a statement about this whole _movement_.

**Comment by licaon-kter** [comment]
Well... https://github.com/pyllyukko/user.js/issues/131#issuecomment-215954058

**Comment by CHEF-KOCH** [comment]
Once it hits any stable (or I know any concept *lol*) then I submit it directly to Mozilla (via email + buftracker + Wiki) so that they will know about this, no excuses! I also found several outdated roadmaps, I will see what we can adapt.

**Comment by CHEF-KOCH** [comment]
I already talked with Mozilla in a group, and after that some stuff was already changed and a lot of more is coming. So overall is/was worth to create a small page to keep an eye on such 'important' things.

My milestone still stands, I hope I can finish the page until then.

**Comment by Roman-Nopantski** [comment]
Can we rename this issue "Connections at Mozilla" - I totally opened the issue expecting a discussion on outbound Firefox connections calling home. Cheers.

**Comment by W4RH4WK** [comment]
Just renamed it, hope you are okay with this @CHEF-KOCH, otherwise just change it again.

@CHEF-KOCH I am quite occupied at the moment and haven't found the time for anything. I am planing to have a more in-depth look at [inox] somewhere in the next month(s). I guess doing this will help figuring out what changes Firefox could benefit from.

[inox]: <https://github.com/gcarq/inox-patchset>

**Comment by Lennium** [comment]
they should add again built inside customization like it was available during Firefox 22. This was THE major strength that you have been able to customize the browser also to a large degree without using add-ons.

**Comment by Emperor-Lestat** [comment]
Yes, we have to make Mozilla listen again to geeks wishes. Perhaps there is still the chance that they listen to reason. Anyway, i can agree with that, that advanced layout features have to be again a part of the core product.

**Comment by Gitoffthelawn** [comment]
@Lennium @Emperor-Lestat Can you put together a list of the customization features that were removed or diminished?

**Comment by Emperor-Lestat** [comment]
Sure, for example the status bar which enabled the user the option to move down almost all button and field elements to it, for example i was able to recreate with it the url bar on the browser bottom.

Or the combination to combine url field, forward/back/refresh/stop buttons with the tab bar, so i got one single united bar

Also small icons, or custom toolbars have been removed, the Firefox button was killed, and the general ability to move UI elements wherever i want to have them have been greatly reduced. Tabs on Bottom have been killed.

In fact all what is not Chrome like was either removed or will be removed soon.

**Comment by Gitoffthelawn** [comment]
@Emperor-Lestat Great list!

I agree completely that it seems that Mozilla is turning Firefox into a static, non-customizable, browser.  This is a mistake, as one of their biggest advantages over the competition has been the level of customization available to the user.

I remember that Firefox used to have a simple *about:config* option to change the width of tabs.  They got rid of it because it was "too hard to maintain".  I felt like they were just making up excuses to do whatever they wanted, even if it was not what users wanted.  C'mon, "too hard to maintain"... that's nonsense.

The solution was having their developers tell users to use CSS overlays to customize the browser.  As such, I became a CSS expert.  But most people won't be willing to do that, nor should they have to, just to customize the tab width.  The trouble with CSS overlays is that they break every time Mozilla changes the underlying code.

Using extensions to add in all the code Mozilla removes is not a good solution.  Although I love extensions, having too many of them generally causes the browser to run slower.  And extensions are often neglected by their developers (once the "fun" wears off), resulting in bugs and compatibility issues.

I would like Mozilla to once again make Firefox *fully* customizable and ensure that extensions will always be able to harness the full power of the browser (something that cannot currently be accomplished with WebExtensions).

**Comment by CHEF-KOCH** [comment]
The main problem is that the WebExtension stuff and possible (the new engine?) not allows much room for customization, this is due security reasons. The problem here is that if you go this way there is no way back because a) compatibility - old stuff will no longer work b) it scares old developers away because no one want to waste yet again time to re-write everything, especially because free addons -> time? c) it's problematically because sandboxed processes are kind of complicated and possible break stuff which needs to be locally re-loaded or you need to cache it which requires more ram usage e.g. for Themes?

Look at this new change, I only can [laugh at this](http://www.ghacks.net/2016/06/11/firefox-page-search-improvements/)? For me it shows the end of the road and that such 'improvements' is as of [an result of no real roadmap](http://www.ghacks.net/2016/06/09/why-firefox-will-continue-to-lose-market-share/). This was once the official 'roadmap' [link](https://wiki.mozilla.org/Releases) - if you see the history it's almost rip and the links only linking to the current FF releases which makes this page kind of redundant. The [real link](https://wiki.mozilla.org/RapidRelease/Calendar) also only reveals when the new versions are coming, it's also kind of useless since no one cares about versions numbers, we more care about the changes and what's coming ...

Sorry that I had to mention this. But I'm a bit disappointed. I already mentioned on ghacks comment that the features which was great in the past are killed one by one.

**Comment by Emperor-Lestat** [comment]
I guess it is necessary to confront the Mozilla guys with all that in a direct IRC talk on their server and present them all this.

And it would be in their best interest to listen.

**Comment by Gitoffthelawn** [comment]
@Emperor-Lestat I like your idea of an IRC conference with Mozilla (perhaps monthly).  I'm in for that.

**Comment by CHEF-KOCH** [comment]
No chat on IRC for me because:
* You don't know which guy is behind and if he isn't only from marketing, I'm not interest in marketing talks because I already know the answers. YES, blah .. we working on it .. blubb (more or less). I'm more interested in a talk with developers and others, because it's more a question what can be done - how many time and if it's worth (I still don't see any e10s hype and I think it's not necessary, because you simply could detect login fields and sandbox on this instead of the entire tab, especially because it's more to protect your data and not against malware).
* IRC has no logging feature, e.g. gitter has, so everyone could see the conversation even after a long time. I'm also unsure, because IRC was never a serious ground to start any talk. I'm also sure Mozilla prefers own stuff like Hello or something. But if you interested you can do, but I'm not joining any IRC talks anymore. 

Well of course I will one day contact Mozilla (again) to talk with them [Milestone 1 or 2] and give them our list but I must ensure that we have (if possible) very good reasons and something to compare, because it's easy to show a list but hard to suggest improvements. This is what we currently not including, we list and complain but we not really explain what exactly 'the user' really wants.

I think mail integration (maybe thunderbird as opt-in) + customization + more focus on the security aspect are the most important things. Thunderbird is another point, would't it be easier to integrate it, I mean overall you need to do some changes exactly the same for Thunderbird and it would maybe cost less time to integrate to e.g. have/get more time for more important stuff. Personally I would love to see this to be integrated in a separated installer which opt-ins Mail support (native, this would also ensure that thunderbird also gets latest security updated automatically.

**Comment by W4RH4WK** [comment]
Since you just mentioned Thunderbird --- I don't think as much has been changed over the past view years in Thunderbird compared to Firefox, but should we try to setup a similar list for Thunderbird too?

**Comment by CHEF-KOCH** [comment]
I not want to complain about everything, Thunderbird itself is fine but it would be the 'next big thing' to minimum get basic email support within Firefox. See Opera, this was a loved feature which everyone (of the old users) missed since they dropped it.

Time is the most important thing in life and development, I only want to see it as developer, it may reduce costs and time and nice you need email for everything, shopping, banking and social media it it's only logical that it gets integrated (imho) because one of the things must run all the time and why not bring all the pieces together?

**Comment by Emperor-Lestat** [comment]
@CHEF-KOCH At least it is a sure thing that people want to have customization and user choice again. Firefox started to shrink in an incredible way after Australis was introduced and features have been removed in favor of possible Chrome abandoning users.

So far Chrome users have also not switched back in a massive way to Firefox.

So, 2 points are more than clear, that Firefox users do not want simplicity and minimalism (users have no problem with minimalism and simplicity as long as customization is built in inside the core product too to turn it on if wanted) and people despise that Mozilla is targeting Chrome as main competitor which was leading in the first place to the removal of features.

The sooner you contact them about that 2 main points, the better. The longer we wait, the higher the chance that Mozilla is really lost.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
To also contribute to this interesting discussion:

Until the end of last year there was a nice Firefox fang-roup on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What is most painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people decide to use against Firefox because they do not want anything Chrome related in Firefox.

**Comment by EMPConway** [comment]
Also contributing to this interesting discussion:

Until the end of last year there was a nice Firefox fan-group on Facebook with around 50 members - and after the annoying stuff Mozilla has done to Firefox in the last few years only around 27 members have been left with using Firefox.

What's painful is that most people who have left switched to Chrome with the reasoning why they should use a lame copy when the original is also around. And a handful of people moved on to Pale Moon, Seamonkey or Vivaldi. Other arguments for switching have been removal of user options or the round tabs and the hamburger button.

So i too think that people who are leaving Firefox are doing it because they do not want anything Chrome related in Firefox.

**Comment by CHEF-KOCH** [comment]
Personally I'm out of this discussion because this is a dead road. I not want or contact Mozilla because one or two things, I hand them over the entire list. The list is also more to get new ideas and to show what the community want, personally I not want to update it each year, if anyone want to do that, feel free. I think I not want to make their work, I spent a lot of time behind the scene to talk with them and I never got anything, not even an thanks. I'm not here to doing the job of others, once I think it's stable and there isn't any room anymore for questions I will do that - and not before. Time is an important factor as mentioned but we need to ensure that there aren't much room for discussions and I can't hand it over yet, because there are too many question marks. 

I also not want to _always_ mention Chrome or other projects because the fear is that they just try to adopt the stuff which makes e.g. Chrome unique, like they tried now (removed theme support and more because upcoming changes or already changes which are done over the last 2 years [e10s, safebrowsing, malware filter, disconnect filter list, ...).

The main counter argument I see now is that (what I already said) we now got another API which isn't easy to revert, you can't Theme or customize something if it not supports it, in Chrome documents it's clearly mentioned that such stuff was explicitly designed to 'reduce developer time'.

> Single architecture investigation
> **Chrome’s unified architecture across platforms minimizes development time but limits our ability to call into native operating system libraries.** 

Overall it means there is no space for customization, which is critical for us because we want this and the first they would response is that this isn't possible.

**Comment by Emperor-Lestat** [comment]
@CHEF-KOCH They could add that kind of support with additional API. But the thing is Mozilla is clearly not interested anymore in offering functions and choice. But they could offer that support if they really still would believe in customization, themes and user choice to have things the way the user wants.

Where does that leave me? Staying with Vivaldi/Otter-Browser or Brave, as a non customizable Firefox is clearly something i do not want and what i am not going to use.

**Comment by CHEF-KOCH** [comment]
> And if Mozilla really is unwilling to change course - where does that leave me?

Chromium. Yeah customizing it's a thing, but we learned from the pass that this can be abused, every single addon/extension/addon/theme possible can be infected or compromised even if they are in the official store. That#s the philosophy behind Chrome, just the pure focus on browsing and security. For me Chromium is one of the best forks, since every beginner can just pickup the pre-compiled binaries which coming out-of-the box with almost the most strongest settings + there exist an no-sync version. 


At this time of writing the clock is ticking and the milestone is almost done, I will improve here and there things but it's nothing much to say or to add here. 

To answer the topic, yes we have connections here, yes it's already under supervision but I not officially submitted it yet (aug. / sept.).

I lock this conversation until we get real process here, otherwise I will close it since the initial question was clearly answered with a 'yes'.
